name: deploy
on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Connect via SSH
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /home/inteligentna/student-debil-bot/content
            git pull
            pm2 reload bot
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          pass: ${{ secrets.PASS }}
